### PR TITLE
Update to newer docker api

### PR DESCRIPTION
**Pull request by mvdbeek**
support python 3 syntax, add ghostscript requirement, fix tempdir handling and many small cleanups.
@drosofff that should be all that is needed to regenerate the figure.

### CODE REVIEW

**Comment by mvdbeek** [comment]
@drosofff TS is updated [here](https://toolshed.g2.bx.psu.edu/repository?repository_id=da21189a3cb9c151&changeset_revision=495946ffc2d6)

**Comment by drosofff** [comment]
Thanks @mvdbeek I'have updated the tools accordingly  in mississippi.

**Comment by mvdbeek** [comment]
@drosofff now the docker version on mississippi is too old :(:
```
docker.errors.APIError: 400 Client Error: Bad Request ("b'client is newer than server (client API version: 1.35, server API version: 1.23)'")
```

**Comment by drosofff** [comment]
@mvdbeek maybe, but strangely the error does not report the right version of current docker on mississippi : 
```
(.venv)galaxy@mississippi:~/galaxy-dist$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by drosofff** [comment]
@mvdbeek is that better with that ?
```
(.venv)galaxy@mississippi:~/galaxy-dist$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:10:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:08:26 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Pull request merged**
